## 15.3 Elements of dynamic programming

### 15.3-1

> Which is a more efficient way to determine the optimal number of multiplications in a matrix-chain multiplication problem: enumerating all the ways of parenthesizing the product and computing the number of multiplications for each, or running RECURSIVE-MATRIX-CHAIN? Justify your answer.

RECURSIVE-MATRIX-CHAIN

### 15.3-2

> Draw the recursion tree for the MERGE-SORT procedure from Section 2.3.1 on an array of 16 elements. Explain why memoization fails to speed up a good divide-and-conquer algorithm such as MERGE-SORT.

It's not overlapping.

### 15.3-3

> Consider a variant of the matrix-chain multiplication problem in which the goal is to parenthesize the sequence of matrices so as to maximize, rather than minimize, the number of scalar multiplications. Does this problem exhibit optimal substructure?

Yes.

### 15.3-4

> As stated, in dynamic programming we first solve the subproblems and then choose which of them to use in an optimal solution to the problem. Professor Capulet claims that we do not always need to solve all the subproblems in order to find an optimal solution. She suggests that we can find an optimal solution to the matrix-chain multiplication problem by always choosing the matrix $A_k$ at which to split the subproduct $A_iA_{i+1} \cdots A_j$ (by selecting $k$ to minimize the quantity $p_{i-1}p_kp_j$) before solving the subproblems. Find an instance of the matrix-chain multiplication problem for which this greedy approach yields a suboptimal solution.

### 15.3-5

> Suppose that in the rod-cutting problem of Section 15.1, we also had limit $l_i$ on the number of pieces of length $i$ that we are allowed to produce, for $i = 1,2, \dots ,n$. Show that the optimal-substructure property described in Section 15.1 no longer holds.

Not independent.

### 15.3-6

> Imagine that you wish to exchange one currency for another. You realize that instead of directly exchanging one currency for another, you might be better off making a series of trades through other currencies, winding up with the currency you want. Suppose that you can trade $n$ different currencies, numbered $1,2,\dots,n$, where you start with currency $1$ and wish to wind up with currency $n$. You are given, for each pair of currencies $i$ and $j$ , an exchange rate $r_{ij}$, meaning that if you start with $d$ units of currency $i$ , you can trade for $dr_{ij}$ units of currency $j$. A sequence of trades may entail a commission, which depends on the number of trades you make. Let $c_k$ be the commission that you are charged when you make $k$ trades. Show that, if $c_k = 0$ for all $k = 1,2, \dots, n$, then the problem of finding the best sequence of exchanges from currency $1$ to currency $n$ exhibits optimal substructure. Then show that if commissions $c_k$ are arbitrary values, then the problem of finding the best sequence of exchanges from currency $1$ to currency $n$ does not necessarily exhibit optimal substructure.

$c_k=0$: $\displaystyle r_{ij} = \max_k{r_{ik} \cdot r_{kj}}$.

If $c_k$ are arbitrary values, then it's not independent.

# Hw
 
Matrix chain multiplication problem

1. recursive 

2. top down with memo 

3. bottom up 


In [7]:
# 1 .recursive 
def recursive_matrix_chain(p,i,j,m):
    if i==j:
        return 0
    
    m[i][j] = float('inf')
    
    for k in range(i, j):
        q = recursive_matrix_chain(p,i,k,m) + recursive_matrix_chain(p,k+1,j,m) + p[i-1]*p[k]*p[j]
        
        if q < m[i][j]:
            m[i][j] = q
        
    return m[i][j]

In [28]:
# 2. top down with memo 
import numpy as np

def memoized_matrix_chain(p):
    n = len(p) - 1 
    m = np.ones([len(p),len(p)])*float('inf')
    
    return lookup_chain(m,p,1,n)

def lookup_chain(m,p,i,j):
    if m[i][j] < float('inf'):
        return m[i][j]
    
    if i == j:
        m[i][j] = 0
        
    else:
        for k in range(i, j):
            q = lookup_chain(m,p,i,k) + lookup_chain(m,p,k+1,j) + p[i-1]*p[k]*p[j]
            
            if q < m[i][j]:
                m[i][j] = q
    #print(m)
    return m[i][j]
   

In [38]:
# 3. bottom up approach 
def matrix_chain_order(p):
    n = len(p) - 1 
    m = np.zeros([len(p),len(p)])
    s = np.zeros([len(p),len(p)])
    for i in range(1,n+1):
        m[i][i] = 0
    for l in range(2,n+1):
        for i in range(n-l+2):
            j = i + l - 1 
            m[i][j] = float('inf')
            for k in range(i,j):
                q = m[i][k] + m[k+1][j] + p[i-1]*p[k]*p[j] 
                if q < m[i][j]:
                    m[i][j] = q
                    # when we have optimal sol ?  s[i][j] = k !  
                    s[i][j] = k 
    return m,s

In [40]:
import numpy as np
p = [30,35,15,5,10,20,25]
m = [[0 for col in range(len(p))] for row in range(len(p))]
# recursive call 을 할때, call 은 (1,6) 부터 하지만, 계산은 overlapping 되며 subproblem 부터 하게 된다. 
""" recursive method"""
print(recursive_matrix_chain(p,1,6,m))
print(np.array(m))

# Top down with memoization 
""" top down method"""
memoized_matrix_chain(p)

# bottom up approach 
""" bottom up method"""
[M,S]= matrix_chain_order(p)
print(M)
print(S)

15125
[[    0     0     0     0     0     0     0]
 [    0     0 15750  7875  9375 11875 15125]
 [    0     0     0  2625  4375  7125 10500]
 [    0     0     0     0   750  2500  5375]
 [    0     0     0     0     0  1000  3500]
 [    0     0     0     0     0     0  5000]
 [    0     0     0     0     0     0     0]]
[[    0. 26250. 27000. 11625. 12875. 15125.     0.]
 [    0.     0. 15750.  7875.  9375. 11875. 15125.]
 [    0.     0.     0.  2625.  4375.  7125. 10500.]
 [    0.     0.     0.     0.   750.  2500.  5375.]
 [    0.     0.     0.     0.     0.  1000.  3500.]
 [    0.     0.     0.     0.     0.     0.  5000.]
 [    0.     0.     0.     0.     0.     0.     0.]]
[[0. 0. 0. 0. 3. 3. 0.]
 [0. 0. 1. 1. 3. 3. 3.]
 [0. 0. 0. 2. 3. 3. 3.]
 [0. 0. 0. 0. 3. 3. 3.]
 [0. 0. 0. 0. 0. 4. 5.]
 [0. 0. 0. 0. 0. 0. 5.]
 [0. 0. 0. 0. 0. 0. 0.]]
