## 15.4 Longest common subsequence

### 15.4-1

> Determine an LCS of $\langle 1, 0, 0, 1, 0, 1, 0, 1\rangle$ and $\langle 0, 1, 0, 1, 1, 0, 1, 1, 0\rangle$.

$\langle 1, 0, 0, 1, 1, 0 \rangle$.

### 15.4-2

> Give pseudocode to reconstruct an LCS from the completed $c$ table and the original sequences $X = \langle x_1, x_2, \dots, x_m \rangle$ and $Y = \langle y_1, y_2, \dots, y_n\rangle$ in $O(m + n)$ time, without using the $b$ table.

```
PRINT-LCS(c, X, Y, i, j)
 1 if c[i][j] == 0
 2     return
 3 if X[i] == Y[j]
 4     PRINT-LCS(c, X, Y, i - 1, j - 1)
 5     print X[i]
 6 elseif c[i - 1][j] > c[i][j - 1]
 7     PRINT-LCS(c, X, Y, i - 1, j)
 8 else
 9     PRINT-LCS(c, X, Y, i, j - 1)
```

### 15.4-3

> Give a memoized version of LCS-LENGTH that runs in $O(mn)$ time.

```
LCS-LENGTH(X, Y, i, j)
 1 if c[i, j] > -1
 2     return c[i, j]
 3 if i == 0 or j == 0
 4     return c[i, j] = 0
 5 if xi = yj
 6     return c[i, j] = LCS-LENGTH(X, Y, i - 1, j - 1) + 1
 7 return c[i, j] = max(LCS-LENGTH(X, Y, i - 1, j), LCS-LENGTH(X, Y, i, j - 1))
```

In [2]:
# bottom up approach 
def LCS_LENGTH(X, Y):
    m = len(X)-1
    n = len(Y)-1
    c = [[-1 for col in range(len(Y))] for row in range(len(X))]
    
    for i in range (1, m+1):
        c[i][0]= 0
    
    for j in range (0, n+1):
        c[0][j] = 0
     
    for i in range(1,m+1):
        for j in range(1,n+1):
            if X[i]==Y[j]:
                c[i][j] = c[i-1][j-1]+1
                #b[i][j] = "↖"
            else:
                c[i][j] = max(c[i-1][j], c[i][j-1])
                
    return c

In [3]:
def PRINT_LCS(c, X, Y, i, j):
    if i==0 or j==0:
        return 
    if X[i]==Y[j]:
        PRINT_LCS(c, X, Y, i - 1, j - 1)
        print(X[i])
    elif c[i - 1][j] >= c[i][j - 1]:
        PRINT_LCS(c, X, Y, i - 1, j)
    else:
        PRINT_LCS(c, X, Y, i, j - 1)

In [4]:
import numpy as np

X = [-1,1,0,0,1,0,1,0,1]        # 크기를 1 값부터 m 값 까지 정해야 하므로 index 0 에 -1 값 을 넣었다.
Y = [-1,0,1,0,1,1,0,1,1,0]
C1 = LCS_LENGTH(X,Y)  
PRINT_LCS(C1, X, Y, len(X)-1, len(Y)-1)
print(np.array(C1))

X2 = [-1,'A','B','C','B','D','A','B']
Y2 = [-1,'B','D','C','A','B','A']
C2 = LCS_LENGTH(X2,Y2)    
PRINT_LCS(C2, X2, Y2, len(X2)-1, len(Y2)-1)
print(np.array(C2))

1
0
0
1
1
0
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 1 1 1]
 [0 1 1 2 2 2 2 2 2 2]
 [0 1 1 2 2 2 3 3 3 3]
 [0 1 2 2 3 3 3 4 4 4]
 [0 1 2 3 3 3 4 4 4 5]
 [0 1 2 3 4 4 4 5 5 5]
 [0 1 2 3 4 4 5 5 5 6]
 [0 1 2 3 4 5 5 6 6 6]]
B
C
B
A
[[0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1]
 [0 1 1 1 1 2 2]
 [0 1 1 2 2 2 2]
 [0 1 1 2 2 3 3]
 [0 1 2 2 2 3 3]
 [0 1 2 2 3 3 4]
 [0 1 2 2 3 4 4]]


### 15.4-4

> Show how to compute the length of an LCS using only $2 \cdot \min(m, n)$ entries in the $c$ table plus $O(1)$ additional space. Then show how to do the same thing, but using $\min(m, n)$ entries plus $O(1)$ additional space.

$2 \cdot \min(m, n)$: rolling.

$\min(m, n)$: save the old value of the last computed position.

### 15.4-5

> Give an $O(n^2)$-time algorithm to find the longest monotonically increasing subsequence of a sequence of $n$ numbers.

Calculate the LCS of the original sequence and the sorted sequence, $O(n \lg n) + O(n^2)=O(n^2)$ time.

### 15.4-6 $\star$

> Give an $O(n \lg n)$-time algorithm to find the longest monotonically increasing subsequence of a sequence of $n$ numbers.

Binary search.