## 15.5 Optimal binary search trees

### 15.5-1

> Write pseudocode for the procedure CONSTRUCT-OPTIMAL-BST$(root)$ which, given the table root, outputs the structure of an optimal binary search tree. For the example in Figure 15.10, your procedure should print out the structure corresponding to the optimal binary search tree shown in Figure 15.9(b).

```
CONSTRUCT-OPTIMAL-BST(root, i, j, last=0)
 1 if i L j
 2     return
 3 if last == 0
 4     print root[i, j] + "is the root"
 5 elseif j < last:
 6     print root[i, j] + "is the left child of" + last
 7 else
 8     print root[i, j] + "is the right child of" + last
 9 CONSTRUCT-OPTIMAL-BST(root, i, root[i, j] - 1, root[i, j])
10 CONSTRUCT-OPTIMAL-BST(root, root[i, j] + 1, j, root[i, j])
```

### 15.5-2

> Determine the cost and structure of an optimal binary search tree for a set of $n = 7$ keys with the following probabilities

$k_4$ is the root
$k_2$ is the left child of $k_4$
$k_1$ is the left child of $k_2$
$d_0$ is the right child of $k_1$
$d_1$ is the right child of $k_1$
$k_3$ is the right child of $k_2$
$d_2$ is the left child of $k_3$
$d_3$ is the right child of $k_3$
$k_5$ is the right child of $k_4$
$d_4$ is the left child of $k_5$
$d_5$ is the right child of $k_5$

### 15.5-3

> Suppose that instead of maintaining the table $w[i, j]$, we computed the value of $w(i, j)$ directly from equation (15.12) in line 9 of OPTIMAL-BST and used this computed value in line 11. How would this change affect the asymptotic running time of OPTIMAL-BST?

$O(n^3)$

### 15.5-4 $\star$

> Knuth [212] has shown that there are always roots of optimal subtrees such that $root[i, j - 1] \le root[i, j] \le root[i + 1, j]$ for all $1 \le i < j \le n$. Use this fact to modify the OPTIMAL-BST procedure to run in $O(n^2)$ time.

```
 10 for r = root[i, j-1] to root[i + 1, j]
```

# Hw

 Optimal Binary Search Tree implementation 
 

In [1]:
def Optimal_BST(p,q,n):
    e = [[0 for j in range(0, n+1)] for i in range(1, n+2+1)]   # 나머지칸을 빈칸으로 두기 위해 i 에 +1 을 하였다. 
    w = [[0 for j in range(0, n+1)] for i in range(1, n+2+1)]
    root = [[0 for j in range(1, n+1+1)] for i in range(1, n+1+1)]
    
    for i in range(1,n+2):
        e[i][i-1] = q[i-1]
        w[i][i-1] = q[i-1]
    
    for l in range(1,n+1):
        for i in range(1,n-l+2):
            j = i+l-1
            e[i][j] = float('inf')     # 무한 대의 값 
            w[i][j] = w[i][j-1] + p[j] + q[j]
            
            for r in range(i, j+1):
                t  = e[i][r-1] + e[r+1][j] + w[i][j]
                
                if t < e[i][j]:
                    e[i][j] = t
                    root[i][j] = r
    
    return e, root  
    

In [2]:
p = [  -1,  0.15,  0.10,  0.05,  0.10,  0.20]
q = [0.05,  0.10,  0.05,  0.05,  0.05,  0.10]
e,root = Optimal_BST(p,q,len(p)-1)
root





[[0, 0, 0, 0, 0, 0],
 [0, 1, 1, 2, 2, 2],
 [0, 0, 2, 2, 2, 4],
 [0, 0, 0, 3, 4, 5],
 [0, 0, 0, 0, 4, 5],
 [0, 0, 0, 0, 0, 5]]

# Hw 2
Martix 를 오른쪽 혹은 밑으로만 이동 하여 끝 점에 도달 할 수 있는가 조사 

top down 방식 

In [3]:
count = 0
count2 = 0

# top down recursively 
def test_nonmemo(i,j,A):
    global count
    count += 1
    print("count: %d" % count)
    
    # 예외: 첫위치 항상 True 
    if (i== 0 and j== 0 ):
        return True
    
    if (i>A.shape[0]-1 or j>A.shape[1]-1):
        return False
    
    is_jump = False
    
    for k in range(i):
        if test_nonmemo(k, j, A): # recursive call vertically 
            if A[k][j] == i - k:
                is_jump = True
    
    for k in range(j):
        if test_nonmemo(i, k, A): # recursive call horizontally 
            if A[i][k] == j - k:
                is_jump = True
        
    return is_jump
    

# top down with memoization    
def test(i,j,A,c):
    global count2
    count2 += 1
    print("count2: %d" % count2)    
    
#     print("test")sd
#     print(i,j)

    # 범위 초과 
    if (i>A.shape[0]-1 or j>A.shape[1]-1):
#         print("debug1")
        return False
    
    # 예외: 첫위치 항상 True 이어야 recursive call 가능하다 
    if (i== 0 and j== 0 ):
        c[i][j] = True
#         print("debug2")
        return True
    
    if c[i][j] != -1:
        return c[i][j]
    
    is_jump = False
    for k in range(i):
        if test(k, j, A, c):    
            if A[k][j] == i - k:
                is_jump = True
    
    for k in range(j):
        if test(i, k, A, c):
            if A[i][k] == j - k:
                is_jump = True
    
    c[i][j] = is_jump
#     print(i,j, is_jump)
    return c[i][j]

def Matrix_Test(A):
    
    c = np.ones(A.shape) * -1
    
    q = test(A.shape[0]-1, A.shape[1]-1,A,c)
    print(c)
    
    return q
            

In [4]:
import numpy as np
A = np.array([[2,3,1,0,0],[0,0,2,0,0],[0,0,0,0,0],[0,0,2,0,0]])
test_nonmemo(A.shape[0]-1, A.shape[1]-1,A)

count: 1
count: 2
count: 3
count: 4
count: 5
count: 6
count: 7
count: 8
count: 9
count: 10
count: 11
count: 12
count: 13
count: 14
count: 15
count: 16
count: 17
count: 18
count: 19
count: 20
count: 21
count: 22
count: 23
count: 24
count: 25
count: 26
count: 27
count: 28
count: 29
count: 30
count: 31
count: 32
count: 33
count: 34
count: 35
count: 36
count: 37
count: 38
count: 39
count: 40
count: 41
count: 42
count: 43
count: 44
count: 45
count: 46
count: 47
count: 48
count: 49
count: 50
count: 51
count: 52
count: 53
count: 54
count: 55
count: 56
count: 57
count: 58
count: 59
count: 60
count: 61
count: 62
count: 63
count: 64
count: 65
count: 66
count: 67
count: 68
count: 69
count: 70
count: 71
count: 72
count: 73
count: 74
count: 75
count: 76
count: 77
count: 78
count: 79
count: 80
count: 81
count: 82
count: 83
count: 84
count: 85
count: 86
count: 87
count: 88
count: 89
count: 90
count: 91
count: 92
count: 93
count: 94
count: 95
count: 96
count: 97
count: 98
count: 99
count: 100
count: 1

True

In [5]:
import numpy as np
A = np.array([[2,3,1,0,0],[0,0,2,0,0],[0,0,0,0,0],[0,0,2,0,0]])
#A = np.array([[2,0,0],[1,0,0],[2,4,5]])
#A = np.array([[2,5,1,6,1,4,1],[6,1,1,2,2,9,3],[7,2,3,2,1,3,1],[1,1,3,1,7,1,2],[4,1,2,3,4,1,2],[3,3,1,2,3,4,1],[1,5,2,9,4,7,0]])
print(A)
q= Matrix_Test(A)
print(q)

[[2 3 1 0 0]
 [0 0 2 0 0]
 [0 0 0 0 0]
 [0 0 2 0 0]]
count2: 1
count2: 2
count2: 3
count2: 4
count2: 5
count2: 6
count2: 7
count2: 8
count2: 9
count2: 10
count2: 11
count2: 12
count2: 13
count2: 14
count2: 15
count2: 16
count2: 17
count2: 18
count2: 19
count2: 20
count2: 21
count2: 22
count2: 23
count2: 24
count2: 25
count2: 26
count2: 27
count2: 28
count2: 29
count2: 30
count2: 31
count2: 32
count2: 33
count2: 34
count2: 35
count2: 36
count2: 37
count2: 38
count2: 39
count2: 40
count2: 41
count2: 42
count2: 43
count2: 44
count2: 45
count2: 46
count2: 47
count2: 48
count2: 49
count2: 50
count2: 51
count2: 52
count2: 53
count2: 54
count2: 55
count2: 56
count2: 57
count2: 58
count2: 59
count2: 60
count2: 61
count2: 62
count2: 63
count2: 64
count2: 65
count2: 66
count2: 67
count2: 68
count2: 69
count2: 70
count2: 71
[[1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1.]]
1.0


bottom up 방식 

In [10]:
def Mtest2(A):
    c = np.ones(A.shape) * -1
    
    # 예외: 첫위치 항상 True 
    c[0][0] = True
        
    for j in range(A.shape[1]):
        for i in range(A.shape[0]):
            for k in range(0,i):
                if c[k][j]:
                    if A[k][j] == i-k:
                        c[i][j] = True

            for k in range(0,j):
                if c[i][k]:
                    if A[i][k] == j-k:
                        c[i][j] = True
                        
    print(c)
    
    if c[A.shape[0]-1][A.shape[0]-1]:
        return True
    else:
        return False
    

In [12]:
import numpy as np
#A = np.array([[2,3,1,0,0],[0,0,2,0,0],[0,0,0,0,0],[0,0,2,0,0]])
A = np.array([[2,5,1,6,1,4,1],[6,1,1,2,2,9,3],[7,2,3,2,1,3,1],[1,1,3,1,7,1,2],[4,1,2,3,4,1,2],[3,3,1,2,3,4,1],[1,5,2,9,4,7,0]])
print(A)
Mtest2(A)

[[2 5 1 6 1 4 1]
 [6 1 1 2 2 9 3]
 [7 2 3 2 1 3 1]
 [1 1 3 1 7 1 2]
 [4 1 2 3 4 1 2]
 [3 3 1 2 3 4 1]
 [1 5 2 9 4 7 0]]
[[ 1. -1.  1.  1. -1.  1.  1.]
 [-1. -1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1. -1.  1. -1.]
 [-1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [-1.  1.  1.  1.  1.  1.  1.]
 [-1.  1.  1.  1.  1. -1.  1.]]


True