### 25.2-2

> Show how to compute the transitive closure using the technique of Section 25.1.

### 25.2-3

> Modify the FLOYD-WARSHALL procedure to compute the $\prod^{(k)}$ matrices according to equations (25.6) and (25.7). Prove rigorously that for all $i \in V$, the predecessor subgraph $G_{\pi, i}$ is a shortest-paths tree with root $i$.

### 25.2-4

> As it appears above, the Floyd-Warshall algorithm requires $\Theta(n^3)$ space, since we compute $d_{ij}^{(k)}$ for $i, j, k = 1, 2, \dots, n$. Show that the following procedure, which simply drops all the superscripts, is correct, and thus only $\Theta(n^2)$ space is required.

### 25.2-5

> Suppose that we modify the way in which equation (25.7) handles equality:

> $$
\pi_{ij}^{(k)} = \left \{ 
\begin{array}{ll}
\pi_{ij}^{(k-1)} & ~\text{if}~ d_{ij}^{(k-1)} < d_{ik}^{(k-1)} + d_{kj}^{(k-1)}, \\
\pi_{kj}^{(k-1)} & ~\text{if}~ d_{ij}^{(k-1)} \ge d_{ik}^{(k-1)} + d_{kj}^{(k-1)}.
\end{array}
\right .
$$

> Is this alternative definition of the predecessor matrix $\prod$ correct?

Correct.

### 25.2-6

> How can we use the output of the Floyd-Warshall algorithm to detect the presence of a negative-weight cycle?

If $D^{(n+1)} \ne D^{(n)}$, then the graph contains negative-weight cycle.

### 25.2-7

> Another way to reconstruct shortest paths in the Floyd-Warshall algorithm uses values $\phi_{ij}^{(k)}$ for $i, j, k = 1, 2, \dots, n$, where $\phi_{ij}^{(k)}$ is the highest-numbered intermediate vertex of a shortest path from $i$ to $j$ in which all intermediate vertices are in the set $\{1, 2, \dots, k \}$. Give a recursive formulation for $\phi_{ij}^{(k)}$, modify the FLOYD-WARSHALL procedure to compute the $\phi_{ij}^{(k)}$ values, and rewrite the PRINT-ALLPAIRS- SHORTEST-PATH procedure to take the matrix $\Phi = (\phi_{ij}^{(n)})$ as an input. How is the matrix $\Phi$ like the $s$ table in the matrix-chain multiplication problem of Section 15.2?

### 25.2-8

> Give an $O(VE)$-time algorithm for computing the transitive closure of a directed
graph $G = (V, E)$.

DFS from each vertex.

### 25.2-9

> Suppose that we can compute the transitive closure of a directed acyclic graph in $f(|V|, |E|)$ time, where $f$ is a monotonically increasing function of $|V|$ and $|E|$. Show that the time to compute the transitive closure $G^* = (V, E^*)$ of a general directed graph $G = (V, E)$ is then $f(|V|, |E|) + O(V + E^*)$.

All the pairs of vertices in one SCC are connected, and the SCCs forms a directed acyclic graph.

# Hw 

Floyd Warshall Algorithm 

Dynamic programming을 어떻게 하느냐에 따라 효율적인 알고리즘을 만들 수 있다. 

running time : O(n^3)

In [1]:
# node로 구현 
class node: 
    
    def __init__(self, name):
        self.name = name
        self.d = 0 
        self.f = 0
        self.pi = 0  
        self.key = 0
        self.color = 'unknown'
        self.edge = {}
        self.number = float('inf')
        
class Graph: 
    
    time = 0
    
    def __init__(self, graph_dict=None, w = None):
        
        # preprocessing
        vertices = list(graph_dict.keys())
        vertices.sort()
        vertices
        
        if graph_dict == None:
            graph_dict = {}
        self.graph_dict = graph_dict
        
        # node object로 list 만듦
        self.nodes = []
        for n in list(vertices):
            self.nodes.append(node(n))
        
        # node object로 dictionary 만듦
        self.nm = {}
        for k in range(len(vertices)):
            self.nm[self.nodes[k].name] = self.nodes[k]
            self.nodes[k].number = k
        
        # edge 를 w 에 의해 부여 
        for j in range(len(vertices)):  # j vertex
            for i in self.graph_dict[self.nodes[j].name]:      # i edge 
                self.nodes[j].edge[i] = w[self.nodes[j].name][i]             # allocate weight 
                
    
    # Graph 의 weight information all pair Matrix return 
    def myweight(self):
        # preprocessing
        vertices = list(self.graph_dict.keys())
        vertices.sort()
        vertices
    
        # node information 
        for v in vertices:
            print("(node.number : ",self.nodes[self.nm[v].number].number, ", node.name : ",self.nodes[self.nm[v].number].name," )" )
        
        import numpy as np
        n = len(self.nodes)
        W = np.ones((n,n))*float('inf')
        
        for i in range(n):
            W[i][i] = 0
        
        for u in self.graph_dict:
            for v in list(self.nm[u].edge):
                if self.nm[u].edge[v] is not None: # from u to v weight
                    W[self.nm[u].number][self.nm[v].number] = self.nm[u].edge[v]
            
        return W
    
    # Graph의 direct edge (0개의 vertex 거치는)Shortest path pi for all pair Information Matrix 
    def myinitialpi(self):
        # preprocessing
        vertices = list(self.graph_dict.keys())
        vertices.sort()
        vertices
        
        for v in vertices:
            print("(node.number : ",self.nodes[self.nm[v].number].number, ", node.name : ",self.nodes[self.nm[v].number].name," )" )
            print(" node.edge : ", self.nodes[self.nm[v].number].edge )

        import numpy as np
        n = len(self.nodes)
        P = np.ones((n,n))*float('inf')
        
        for u in vertices:
            for v in list(self.nm[u].edge):
                if self.nm[u].edge[v] is not None: # from u to v weight
                    P[self.nm[u].number][self.nm[v].number] =(self.nm[u].number) 
        
        return P 

In [2]:
g = {'a': set(['b','c','e']),
     'b': set(['d','e']),
     'c': set(['b']),
     'd': set(['a','c']),
     'e': set(['d'])}

w = {'a': {'b':3, 'c':8, 'e':-4},
     'b': {'d':1, 'e':7},
     'c': {'b':4},
     'd': {'a':2, 'c':-5},
     'e': {'d':6}}


G = Graph(g,w)

In [3]:
import numpy as np
from time import * 

""" running time : tree nested loop 이므로 O(n^3) : entry를 n*n*n 에 대해 채워넣어야한다."""
def floyd_warshall(W):
    start_time = time()
    n = len(W)
    D = np.ones((n,n,n))
    D[0] = W
    Dnk = D[0]
    Df = np.ones((n,n))
    
    # procedure 는 k = 1 부터 n 이고 python은 index 0~n-1 이기 때문에 약간 복잡하다. 
    for k in range(n):
        D[k] = Dnk # Next iteration 먼저 계산 
        for i in range(n):
            for j in range(n):
                Dnk[i][j] = min(D[k][i][j], D[k][i][k] + D[k][k][j])  
                Df[i][j] = Dnk[i][j]
    D[0] = W
    print("D array :  \n", D) 
    print("---it takes %s seconds ---" % (time() - start_time))
    return Df # final shrotest path info, when k == n 

def floyd_warshall_with_P(G):
    W= G.myweight()
    P0 = G.myinitialpi() 
    
    n = len(W)
    D = np.ones((n,n,n))
    P = np.ones((n,n,n))
    D[0] = W
    P[0] = P0
    Dnk = D[0]
    Pnk = P[0]
    Df = np.ones((n,n))
    Pf = np.ones((n,n))
    
    # procedure 는 k = 1 부터 n 이고 python은 index 0~n-1 이기 때문에 약간 복잡하다. 
    for k in range(n):
        D[k] = Dnk # Next iteration 먼저 계산
        P[k] = Pnk
        for i in range(n):
            for j in range(n):
                if D[k][i][j] <= (D[k][i][k] + D[k][k][j]): 
                    Dnk[i][j] = D[k][i][j]
                    Pnk[i][j] = P[k][i][j]
                    
                    Df[i][j] = Dnk[i][j]
                    Pf[i][j] = Pnk[i][j]
                else: 
                    Dnk[i][j] = D[k][i][k] + D[k][k][j]
                    Pnk[i][j] = P[k][k][j]     

                    Df[i][j] = Dnk[i][j]
                    Pf[i][j] = Pnk[i][j]
    
    D[0] = W
    P[0] = P0
    print("D array :  \n", D) 
    print("P array :  \n", P)
    return Df, Pf # final shrotest path info, when k == n 

In [4]:
W = G.myweight()
print(W)
P = G.myinitialpi()  # when k = 0
print(P)

(node.number :  0 , node.name :  a  )
(node.number :  1 , node.name :  b  )
(node.number :  2 , node.name :  c  )
(node.number :  3 , node.name :  d  )
(node.number :  4 , node.name :  e  )
[[ 0.  3.  8. inf -4.]
 [inf  0. inf  1.  7.]
 [inf  4.  0. inf inf]
 [ 2. inf -5.  0. inf]
 [inf inf inf  6.  0.]]
(node.number :  0 , node.name :  a  )
 node.edge :  {'b': 3, 'e': -4, 'c': 8}
(node.number :  1 , node.name :  b  )
 node.edge :  {'e': 7, 'd': 1}
(node.number :  2 , node.name :  c  )
 node.edge :  {'b': 4}
(node.number :  3 , node.name :  d  )
 node.edge :  {'c': -5, 'a': 2}
(node.number :  4 , node.name :  e  )
 node.edge :  {'d': 6}
[[inf  0.  0. inf  0.]
 [inf inf inf  1.  1.]
 [inf  2. inf inf inf]
 [ 3. inf  3. inf inf]
 [inf inf inf  4. inf]]


In [5]:
Df = floyd_warshall(W)
print(Df)

D array :  
 [[[ 0.  3.  8. inf -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0. inf inf]
  [ 2. inf -5.  0. inf]
  [inf inf inf  6.  0.]]

 [[ 0.  3.  8. inf -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0. inf inf]
  [ 2.  5. -5.  0. -2.]
  [inf inf inf  6.  0.]]

 [[ 0.  3.  8.  4. -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0.  5. 11.]
  [ 2.  5. -5.  0. -2.]
  [inf inf inf  6.  0.]]

 [[ 0.  3.  8.  4. -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0.  5. 11.]
  [ 2. -1. -5.  0. -2.]
  [inf inf inf  6.  0.]]

 [[ 0.  3. -1.  4. -4.]
  [ 3.  0. -4.  1. -1.]
  [ 7.  4.  0.  5.  3.]
  [ 2. -1. -5.  0. -2.]
  [ 8.  5.  1.  6.  0.]]]
---it takes 0.003004312515258789 seconds ---
[[ 0.  1. -3.  2. -4.]
 [ 3.  0. -4.  1. -1.]
 [ 7.  4.  0.  5.  3.]
 [ 2. -1. -5.  0. -2.]
 [ 8.  5.  1.  6.  0.]]


In [6]:
[D,P] = floyd_warshall_with_P(G)
print ("##################  All pair shortest path info ##############################")
print(D)
print(P)

(node.number :  0 , node.name :  a  )
(node.number :  1 , node.name :  b  )
(node.number :  2 , node.name :  c  )
(node.number :  3 , node.name :  d  )
(node.number :  4 , node.name :  e  )
(node.number :  0 , node.name :  a  )
 node.edge :  {'b': 3, 'e': -4, 'c': 8}
(node.number :  1 , node.name :  b  )
 node.edge :  {'e': 7, 'd': 1}
(node.number :  2 , node.name :  c  )
 node.edge :  {'b': 4}
(node.number :  3 , node.name :  d  )
 node.edge :  {'c': -5, 'a': 2}
(node.number :  4 , node.name :  e  )
 node.edge :  {'d': 6}
D array :  
 [[[ 0.  3.  8. inf -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0. inf inf]
  [ 2. inf -5.  0. inf]
  [inf inf inf  6.  0.]]

 [[ 0.  3.  8. inf -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0. inf inf]
  [ 2.  5. -5.  0. -2.]
  [inf inf inf  6.  0.]]

 [[ 0.  3.  8.  4. -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0.  5. 11.]
  [ 2.  5. -5.  0. -2.]
  [inf inf inf  6.  0.]]

 [[ 0.  3.  8.  4. -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0.  5. 11.]
  [ 2. -1. -5.  0. -