## 25.1 Shortest paths and matrix multiplication

### 25.1-1

> Run SLOW-ALL-PAIRS-SHORTEST-PATHS on the weighted, directed graph of Figure 25.2, showing the matrices that result for each iteration of the loop. Then do the same for FASTER-ALL-PAIRS-SHORTEST-PATHS.

Initial:

$$
\left \{ \begin{matrix}
0 & \infty & \infty & \infty & -1 & \infty\\
1 & 0 & \infty & 2 & \infty & \infty\\
\infty & 2 & 0 & \infty & \infty & -8\\
-4 & \infty & \infty & 0 & 3 & \infty\\
\infty & 7 & \infty & \infty & 0 & \infty\\
\infty & 5 & 10 & \infty & \infty & 0\\
\end{matrix} \right \}
$$
Slow:

$m=2$:
$$
\left \{ \begin{matrix}
0 & 6 & \infty & \infty & -1 & \infty\\
-2 & 0 & \infty & 2 & 0 & \infty\\
3 & -3 & 0 & 4 & \infty & -8\\
-4 & 10 & \infty & 0 & -5 & \infty\\
8 & 7 & \infty & 9 & 0 & \infty\\
6 & 5 & 10 & 7 & \infty & 0\\
\end{matrix} \right \}
$$

$m=3$:
$$
\left \{ \begin{matrix}
0 & 6 & \infty & 8 & -1 & \infty\\
-2 & 0 & \infty & 2 & -3 & \infty\\
-2 & -3 & 0 & -1 & 2 & -8\\
-4 & 2 & \infty & 0 & -5 & \infty\\
5 & 7 & \infty & 9 & 0 & \infty\\
3 & 5 & 10 & 7 & 5 & 0\\
\end{matrix} \right \}
$$

$m=4$:
$$
\left \{ \begin{matrix}
0 & 6 & \infty & 8 & -1 & \infty\\
-2 & 0 & \infty & 2 & -3 & \infty\\
-5 & -3 & 0 & -1 & -3 & -8\\
-4 & 2 & \infty & 0 & -5 & \infty\\
5 & 7 & \infty & 9 & 0 & \infty\\
3 & 5 & 10 & 7 & 2 & 0\\
\end{matrix} \right \}
$$

$m=5$:
$$
\left \{ \begin{matrix}
0 & 6 & \infty & 8 & -1 & \infty\\
-2 & 0 & \infty & 2 & -3 & \infty\\
-5 & -3 & 0 & -1 & -6 & -8\\
-4 & 2 & \infty & 0 & -5 & \infty\\
5 & 7 & \infty & 9 & 0 & \infty\\
3 & 5 & 10 & 7 & 2 & 0\\
\end{matrix} \right \}
$$
Fast:

$m=2$:
$$
\left \{ \begin{matrix}
0 & 6 & \infty & \infty & -1 & \infty\\
-2 & 0 & \infty & 2 & 0 & \infty\\
3 & -3 & 0 & 4 & \infty & -8\\
-4 & 10 & \infty & 0 & -5 & \infty\\
8 & 7 & \infty & 9 & 0 & \infty\\
6 & 5 & 10 & 7 & \infty & 0\\
\end{matrix} \right \}
$$

$m=4$:
$$
\left \{ \begin{matrix}
0 & 6 & \infty & 8 & -1 & \infty\\
-2 & 0 & \infty & 2 & -3 & \infty\\
-5 & -3 & 0 & -1 & -3 & -8\\
-4 & 2 & \infty & 0 & -5 & \infty\\
5 & 7 & \infty & 9 & 0 & \infty\\
3 & 5 & 10 & 7 & 2 & 0\\
\end{matrix} \right \}
$$

$m=8$:
$$
\left \{ \begin{matrix}
0 & 6 & \infty & 8 & -1 & \infty\\
-2 & 0 & \infty & 2 & -3 & \infty\\
-5 & -3 & 0 & -1 & -6 & -8\\
-4 & 2 & \infty & 0 & -5 & \infty\\
5 & 7 & \infty & 9 & 0 & \infty\\
3 & 5 & 10 & 7 & 2 & 0\\
\end{matrix} \right \}
$$

### 25.1-2

> Why do we require that $w_{ii}=0$ for all $1 \le i \le n$?

To simplify (25.2).

### 25.1-3

> What does the matrix

> $$
L^{(0)} = \left ( \begin{matrix}
0 & \infty & \infty & \cdots & \infty \\
\infty & 0 & \infty & \cdots & \infty \\
\infty & \infty & 0 & \cdots & \infty \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
\infty & \infty & \infty & \cdots & 0 \\
\end{matrix} \right )
$$

> used in the shortest-paths algorithms correspond to in regular matrix multiplication?

Unit.

### 25.1-4

> Show that matrix multiplication defined by EXTEND-SHORTEST-PATHS is associative.

### 25.1-5

> Show how to express the single-source shortest-paths problem as a product of matrices and a vector. Describe how evaluating this product corresponds to a Bellman-Ford-like algorithm (see Section 24.1).

A vector filled with 0 except that the source is 1.

### 25.1-6

> Suppose we also wish to compute the vertices on shortest paths in the algorithms of this section. Show how to compute the predecessor matrix $\prod$ from the completed matrix $L$ of shortest-path weights in $O(n^3)$ time.

If $l_{ik} + w_{kj} = l_{ij}$, then $\pi_{ij} = k$.

### 25.1-7

> We can also compute the vertices on shortest paths as we compute the shortestpath weights. Define $\pi_{ij}^{(m)}$ as the predecessor of vertex $j$ on any minimum-weight path from $i$ to $j$ that contains at most $m$ edges. Modify the EXTEND-SHORTESTPATHS and SLOW-ALL-PAIRS-SHORTEST-PATHS procedures to compute the matrices$\prod^{(1)}, \prod^{(2)}, \dots, \prod^{(n-1)}$ as the matrices $L^{(1)}, L^{(2)}, \dots, L^{(n-1)}$ are computed.

If $l_{ik}^{(m-1)} + w_{kj} < l_{ij}^{(m)}$, then $\pi_{ij}^{(m)} = k$.

### 25.1-8

> The FASTER-ALL-PAIRS-SHORTEST-PATHS procedure, as written, requires us to store $\lceil \lg (n - 1) \rceil$ matrices, each with $n^2$ elements, for a total space requirement of $\Theta(n^2 \lg n)$. Modify the procedure to require only $\Theta(n^2)$ space by using only two $n \times n$ matrices.

In [ ]:
def fast_all_pairs_shortest_paths(w):
    n = len(w)
    m = 1
    while m < n - 1:
        w = extend_shortest_paths(w, w)
        m *= 2
    return w

### 25.1-9

> Modify FASTER-ALL-PAIRS-SHORTEST-PATHS so that it can determine whether
the graph contains a negative-weight cycle.

If $l_{ii} < 0$, then there is a negative-weight cycle.

### 25.1-10

> Give an efficient algorithm to find the length (number of edges) of a minimum-length negative-weight cycle in a graph.

If $l_{ii}^{(m)} < 0$ and $l_{ii}^{(m-1)} = 0$, then the minimum-length is $m$.

# Hw

Finding all pair shortest path 

graph's node has a number 

    self.nodes[G.nm[v].number].number 

graph class has W matrix make function 

def Myweight():
    if self.nm[u].edge[v] is not None: # from u to v weight
        W[self.nm[u].number][self.nm[v].number] = self.nm[u].edge[v]
        
        


In [1]:
# node로 구현 
class node: 
    
    def __init__(self, name):
        self.name = name
        self.d = 0 
        self.f = 0
        self.pi = 0  
        self.key = 0
        self.color = 'unknown'
        self.edge = {}
        self.number = float('inf')
        
class Graph: 
    
    time = 0
    
    def __init__(self, graph_dict=None, w = None):
        
        # preprocessing
        vertices = list(graph_dict.keys())
        vertices.sort()
        vertices
        
        if graph_dict == None:
            graph_dict = {}
        self.graph_dict = graph_dict
        
        # node object로 list 만듦
        self.nodes = []
        for n in list(vertices):
            self.nodes.append(node(n))
        
        # node object로 dictionary 만듦
        self.nm = {}
        for k in range(len(vertices)):
            self.nm[self.nodes[k].name] = self.nodes[k]
            self.nodes[k].number = k
        
        # edge 를 w 에 의해 부여 
        for j in range(len(vertices)):  # j vertex
            for i in self.graph_dict[self.nodes[j].name]:      # i edge 
                self.nodes[j].edge[i] = w[self.nodes[j].name][i]             # allocate weight 
                
    
    # Graph 의 weight information Matrix return 
    def myweight(self):
        # preprocessing
        vertices = list(self.graph_dict.keys())
        vertices.sort()
        vertices
    
        # node information 
        for v in vertices:
            print("(node.number : ",self.nodes[self.nm[v].number].number, ", node.name : ",self.nodes[self.nm[v].number].name," )" )
        
        import numpy as np
        n = len(self.nodes)
        W = np.ones((n,n))*float('inf')
        
        for i in range(n):
            W[i][i] = 0
        
        for u in self.graph_dict:
            for v in list(self.nm[u].edge):
                if self.nm[u].edge[v] is not None: # from u to v weight
                    W[self.nm[u].number][self.nm[v].number] = self.nm[u].edge[v]
            
        return W

In [2]:
g = {'a': set(['b','c','e']),
     'b': set(['d','e']),
     'c': set(['b']),
     'd': set(['a','c']),
     'e': set(['d'])}

w = {'a': {'b':3, 'c':8, 'e':-4},
     'b': {'d':1, 'e':7},
     'c': {'b':4},
     'd': {'a':2, 'c':-5},
     'e': {'d':6}}


G = Graph(g,w)

In [3]:
import numpy as np 
from time import *  

""" compute L' <= L using W  // running time : O(n^3)"""
def extend_shortest_paths(L,W):
    n = len(L)
    nL = np.ones((n,n))
    
    for i in range(n):
        for j in range(n):
            nL[i][j] = float('inf')
            for k in range(n):
                nL[i][j] = min(nL[i][j], L[i][k] + W[k][j])
    return nL

""" compute L(n-1) // running time : O(n^4) bottom up approach(DP) """
def show_all_pairs_shortest_paths(W):
    start_time = time()
    n = len(W)
    L1 = W
    Lpm = L1                                  #Lpm = Lm-1 meanning  
    for m in range(2,n):
        Lm = np.ones((n,n))
        Lm = extend_shortest_paths(Lpm,W)
        Lpm = Lm
    print("---it takes %s seconds ---" % (time() - start_time))
    return Lm 

""" L(n-1 ) 이 shortest path weight 이므로, 그 이후 아무리 계산해도, 변하지 않음을 이용하여 
    running time 개선 : O(n^3 × lgn)"""
def faster_all_pairs_shortest_paths(W):
    start_time = time()
    n = len(W)
    L1 = W
    Lm = L1
    m = 1
    while m < n - 1:                                      # this loop takes O(lgn * n^3)
        L2m = np.ones((n,n))
        L2m = extend_shortest_paths(Lm,Lm)                # O(n^3)
        Lm = L2m
        m = m*2
    print("---it takes %s seconds ---" % (time() - start_time))
    return Lm 

In [4]:
W = G.myweight()
print(W)

(node.number :  0 , node.name :  a  )
(node.number :  1 , node.name :  b  )
(node.number :  2 , node.name :  c  )
(node.number :  3 , node.name :  d  )
(node.number :  4 , node.name :  e  )
[[ 0.  3.  8. inf -4.]
 [inf  0. inf  1.  7.]
 [inf  4.  0. inf inf]
 [ 2. inf -5.  0. inf]
 [inf inf inf  6.  0.]]


In [5]:
result1 = extend_shortest_paths(W,W)
result1

array([[ 0.,  3.,  8.,  2., -4.],
       [ 3.,  0., -4.,  1.,  7.],
       [inf,  4.,  0.,  5., 11.],
       [ 2., -1., -5.,  0., -2.],
       [ 8., inf,  1.,  6.,  0.]])

In [6]:
result2 = show_all_pairs_shortest_paths(W)
result2

---it takes 0.0009989738464355469 seconds ---


array([[ 0.,  1., -3.,  2., -4.],
       [ 3.,  0., -4.,  1., -1.],
       [ 7.,  4.,  0.,  5.,  3.],
       [ 2., -1., -5.,  0., -2.],
       [ 8.,  5.,  1.,  6.,  0.]])

In [7]:
result3 = faster_all_pairs_shortest_paths(W)
result3

---it takes 0.001001119613647461 seconds ---


array([[ 0.,  1., -3.,  2., -4.],
       [ 3.,  0., -4.,  1., -1.],
       [ 7.,  4.,  0.,  5.,  3.],
       [ 2., -1., -5.,  0., -2.],
       [ 8.,  5.,  1.,  6.,  0.]])